# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='prize',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
