# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import raffle.models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0004_auto_20161123_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_1', models.ImageField(upload_to=raffle.models.get_board_folder_path)),
                ('banner_2', models.ImageField(upload_to=raffle.models.get_board_folder_path)),
                ('banner_3', models.ImageField(upload_to=raffle.models.get_board_folder_path)),
                ('banner_4', models.ImageField(upload_to=raffle.models.get_board_folder_path)),
            ],
        ),
    ]
